const LABELS: Record<string, string> = {
  tool: '工具', workflow: '工作流程', runtime: '运行环境',
  vimax_narrative_planning: '叙事规划', vimax_novel_planning: '小说规划', vimax_render_video: '视频渲染',
  read_file: '读取文件', write_file: '写入文件', read_json: '读取结构化数据', write_json: '写入结构化数据',
  list_files: '列出文件', glob_files: '查找文件', search_text: '搜索文本', view_image: '查看图像',
  memory_read: '读取偏好', memory_write: '保存偏好', todo_read: '读取待办', todo_write: '更新待办',
  run_shell: '执行命令', sleep: '等待',
  created: '已创建', starting: '正在启动', running: '正在执行', completed: '已完成', failed: '执行失败',
  interrupted: '已中断', rendering: '正在渲染', revising: '正在修订',
  pending: '等待中', queued: '排队中', processing: '正在处理', in_progress: '正在进行',
  cancelled: '已取消', expired: '已过期', ready: '已就绪', error: '出错',
  initializing_llm: '正在初始化语言模型', chat_model_ready: '语言模型已就绪',
  idea_pipeline_ready: '创意工作流已就绪', script_pipeline_ready: '剧本工作流已就绪',
  develop_story: '构思故事', extract_characters: '提取角色', write_script: '编写剧本',
  plan_script: '规划剧本', plan_scene: '规划场景', planning_failed: '规划失败',
  design_storyboard: '设计分镜', generate_frames: '生成画面',
  decompose_shots: '拆解镜头', construct_camera_tree: '构建机位规划', construct_camera_tree_retry: '重试机位规划',
  render_start: '开始渲染', render_done: '渲染完成', render_failed: '渲染失败',
  load_storyboard: '加载分镜', storyboard_ready: '分镜已就绪',
  load_shot_descriptions: '加载镜头描述', shot_descriptions_ready: '镜头描述已就绪',
  load_camera_tree: '加载机位规划', camera_tree_ready: '机位规划已就绪',
  frames_start: '开始生成画面', camera_frames_start: '开始生成机位画面', camera_frames_done: '机位画面已就绪',
  frame_start: '正在生成画面', frame_done: '画面已生成', frame_exists: '画面已存在',
  frame_prompt_start: '正在选择画面参考', frame_prompt_done: '画面参考已选好', frame_prompt_exists: '画面提示词已存在',
  video_clips_start: '开始生成视频片段', video_clip_start: '正在生成视频片段',
  video_clip_done: '视频片段已生成', video_clip_exists: '视频片段已存在', video_clip_waiting_for_frames: '等待镜头画面',
  concat_start: '正在合成视频', concat_done: '视频合成完成', final_video_exists: '最终视频已存在',
  transition_video_start: '正在生成转场视频', transition_video_done: '转场视频已生成', transition_video_exists: '转场视频已存在',
  new_camera_image_start: '正在提取新机位画面', new_camera_image_done: '新机位画面已提取', new_camera_image_exists: '新机位画面已存在',
  character_portraits_start: '正在生成角色参考图', character_portraits_done: '角色参考图已就绪',
  character_portraits_exist: '角色参考图已存在', character_portraits_loaded: '已加载角色参考图',
  character_portrait_start: '正在生成角色参考图', character_portrait_done: '角色参考图已就绪',
  character_portrait_front_start: '正在生成角色正面照', character_portrait_front_done: '角色正面照已生成',
  character_portrait_side_start: '正在生成角色侧面照', character_portrait_side_done: '角色侧面照已生成',
  character_portrait_back_start: '正在生成角色背面照', character_portrait_back_done: '角色背面照已生成',
  video_create: '正在创建视频任务', video_task_created: '视频任务已创建', video_create_error: '视频任务创建失败',
  video_query_error: '视频状态查询失败', video_status: '视频生成状态',
  video_download_start: '正在下载视频', video_completed: '视频生成完成',
  novel_plan_text_artifacts: '规划小说文档', save_novel: '保存小说', compress_novel: '压缩小说',
  extract_events: '提取事件', retrieve_chunks: '检索相关片段', extract_scenes: '提取场景', merge_characters: '合并角色',
  novel_render_load: '加载小说规划', novel_portraits_start: '生成小说角色参考图',
  novel_portraits_base_done: '基础角色参考图已就绪', novel_portraits_scene_start: '生成场景角色参考图',
  novel_portraits_done: '场景角色参考图已就绪', novel_scene_render_start: '渲染小说场景',
  novel_scene_render_done: '小说场景渲染完成', novel_render_completed: '小说视频渲染完成',
};

const MESSAGES: Record<string, string> = {
  Starting: '正在启动', Completed: '已完成',
  'Starting narrative planning': '开始叙事规划',
  'Initializing bounded chat model': '正在初始化语言模型',
  'Bounded chat model initialized': '语言模型已初始化',
  'Idea pipeline initialized': '创意工作流已初始化',
  'Script pipeline initialized': '剧本工作流已初始化',
  'Developing story from user idea': '根据创意构思故事',
  'Extracting characters from story': '从故事中提取角色',
  'Extracting characters from script': '从剧本中提取角色',
  'Using provided characters': '使用已有角色',
  'Writing scene scripts from story': '根据故事编写场景剧本',
  'Planning storyboard and shots from provided script': '根据剧本规划分镜和镜头',
  'Narrative planning failed; partial artifacts were kept': '叙事规划失败，已保留部分产物',
  'Narrative planning complete': '叙事规划完成',
  'Revising structured text artifact': '正在修订规划文档',
  'Starting novel planning': '开始小说规划',
  'Planning novel structured text artifacts': '正在规划小说文档',
  'Novel planning complete': '小说规划完成',
  'Starting video render': '开始渲染视频',
  'Render failed; partial artifacts were kept': '渲染失败，已保留部分产物',
  'Starting script2video render': '开始将剧本渲染为视频',
  'Loading or designing storyboard': '正在加载或设计分镜',
  'Designing storyboard': '正在设计分镜',
  'Decomposing shot visual descriptions': '正在拆解镜头画面描述',
  'Constructing camera tree': '正在构建机位规划',
  'Retrying camera tree construction after schema/type failure': '机位数据格式或类型不匹配，正在重新构建',
  'Storyboard ready': '分镜已就绪',
  'Loading or decomposing shot descriptions': '正在加载或拆解镜头描述',
  'Shot descriptions ready': '镜头描述已就绪',
  'Loading or constructing camera tree': '正在加载或构建机位规划',
  'Camera tree ready': '机位规划已就绪',
  'Generating frames': '正在生成画面',
  'Generating frames for cameras': '正在生成机位画面',
  'Generating video clips for shots': '正在生成镜头视频片段',
  'Script2video render complete': '剧本视频渲染完成',
  'Extracting characters before render': '渲染前提取角色',
  'Using provided characters for render': '使用已有角色进行渲染',
  'Final video already exists': '最终视频已存在',
  'Concatenating video clips': '正在合成视频片段',
  'Final video concatenated': '最终视频已合成',
  'Completed character portrait generation': '角色参考图生成完成',
  'All character portraits already exist': '所有角色参考图均已存在',
  'Loaded existing character portraits': '已加载现有角色参考图',
  'Generating character portraits': '正在生成角色参考图',
  'Character portraits ready': '角色参考图已就绪',
  'OpenRouter video generation task created': 'OpenRouter 视频任务已创建',
  'Downloading OpenRouter video output': '正在下载 OpenRouter 视频',
  'OpenRouter video generation completed and downloaded': 'OpenRouter 视频已生成并下载',
  'Video generation task created': '视频任务已创建',
  'Video query failed': '视频状态查询失败',
  'Video generation completed': '视频生成完成',
  'Saving and splitting novel text': '正在保存并拆分小说文本',
  'Compressing novel chunks': '正在压缩小说片段',
  'Extracting events from compressed novel': '正在从压缩后的小说中提取事件',
  'Retrieving relevant chunks for events': '正在检索事件相关片段',
  'Extracting screenplay scenes': '正在提取剧本场景',
  'Merging scene characters into novel-level characters': '正在合并各场景中的角色信息',
  'Novel structured text planning complete': '小说文档规划完成',
  'Loading novel structured text artifacts': '正在加载小说规划文档',
  'Generating novel character portraits': '正在生成小说角色参考图',
  'Base character portraits ready': '基础角色参考图已就绪',
  'Generating scene character portraits': '正在生成场景角色参考图',
  'Scene character portraits ready': '场景角色参考图已就绪',
  'Rendering novel scene video': '正在渲染小说场景视频',
  'Rendered novel scene video': '小说场景视频已渲染',
  'Novel scene render complete': '小说场景渲染完成',
  'Starting shell command': '正在启动命令',
  'Configuration updated': '配置已更新',
  'Generation stopped': '生成已停止',
  'Switching workspace': '正在切换工作区',
};

const FRAME_LABELS: Record<string, string> = {first_frame: '首帧', last_frame: '尾帧', 'first frame': '首帧', 'First frame': '首帧'};
const PORTRAIT_LABELS: Record<string, string> = {front: '正面照', side: '侧面照', back: '背面照'};
const numbered = (value: string) => Number(value) + 1;

const MESSAGE_PATTERNS: Array<[RegExp, (...values: string[]) => string]> = [
  [/^Planning scene (\d+) storyboard and shots$/, (scene) => `正在规划场景 ${numbered(scene)} 的分镜和镜头`],
  [/^Generating frames for camera (\d+)$/, (camera) => `正在生成机位 ${numbered(camera)} 的画面`],
  [/^Frames for camera (\d+) ready$/, (camera) => `机位 ${numbered(camera)} 的画面已就绪`],
  [/^Generating portraits for (.+)$/, (name) => `正在生成 ${name} 的参考图`],
  [/^Portraits for (.+) ready$/, (name) => `${name} 的参考图已就绪`],
  [/^Generating (front|side|back) portrait for (.+)$/, (view, name) => `正在生成 ${name} 的${PORTRAIT_LABELS[view]}`],
  [/^Generated (front|side|back) portrait for (.+)$/, (view, name) => `已生成 ${name} 的${PORTRAIT_LABELS[view]}`],
  [/^(First frame|first_frame|last_frame) for shot (\d+) already exists$/, (frame, shot) => `镜头 ${numbered(shot)} 的${FRAME_LABELS[frame]}已存在`],
  [/^Generating (first frame|first_frame|last_frame) for shot (\d+)$/, (frame, shot) => `正在生成镜头 ${numbered(shot)} 的${FRAME_LABELS[frame]}`],
  [/^Generated (first frame|first_frame|last_frame) for shot (\d+)$/, (frame, shot) => `已生成镜头 ${numbered(shot)} 的${FRAME_LABELS[frame]}`],
  [/^First frame prompt for shot (\d+) already exists$/, (shot) => `镜头 ${numbered(shot)} 的首帧提示词已存在`],
  [/^Prompt for (first_frame|last_frame) of shot (\d+) already exists$/, (frame, shot) => `镜头 ${numbered(shot)} 的${FRAME_LABELS[frame]}提示词已存在`],
  [/^Selecting references for (first frame|first_frame|last_frame) of shot (\d+)$/, (frame, shot) => `正在选择镜头 ${numbered(shot)} 的${FRAME_LABELS[frame]}参考图`],
  [/^Selected references for (first frame|first_frame|last_frame) of shot (\d+)$/, (frame, shot) => `已选好镜头 ${numbered(shot)} 的${FRAME_LABELS[frame]}参考图`],
  [/^Video clip for shot (\d+) already exists$/, (shot) => `镜头 ${numbered(shot)} 的视频片段已存在`],
  [/^Waiting for frames before video clip (\d+)$/, (shot) => `正在等待镜头 ${numbered(shot)} 的画面，以生成视频片段`],
  [/^Generating video clip for shot (\d+)$/, (shot) => `正在生成镜头 ${numbered(shot)} 的视频片段`],
  [/^Generated video clip for shot (\d+)$/, (shot) => `已生成镜头 ${numbered(shot)} 的视频片段`],
  [/^Transition video for shot (\d+) already exists$/, (shot) => `镜头 ${numbered(shot)} 的转场视频已存在`],
  [/^Generating transition video for shot (\d+)$/, (shot) => `正在生成镜头 ${numbered(shot)} 的转场视频`],
  [/^Transition video for shot (\d+) generated$/, (shot) => `镜头 ${numbered(shot)} 的转场视频已生成`],
  [/^New camera image for shot (\d+) already exists$/, (shot) => `镜头 ${numbered(shot)} 的新机位画面已存在`],
  [/^Extracting new camera image for shot (\d+)$/, (shot) => `正在提取镜头 ${numbered(shot)} 的新机位画面`],
  [/^New camera image for shot (\d+) extracted$/, (shot) => `镜头 ${numbered(shot)} 的新机位画面已提取`],
  [/^Creating (OpenRouter )?video generation task with (.+)$/, (provider, model) => `正在使用 ${model} 创建${provider ? ' OpenRouter ' : ''}视频任务`],
  [/^(OpenRouter )?[Vv]ideo generation status: (.+)$/, (provider, status) => `${provider || ''}视频生成状态：${activityLabel(status)}`],
  [/^Video create attempt (\d+) failed$/, (attempt) => `第 ${attempt} 次创建视频任务失败`],
  [/^Sleeping for ([\d.]+)s$/, (seconds) => `等待 ${seconds} 秒`],
];

export function activityLabel(value: string): string {
  const key = value.toLowerCase();
  if (Object.hasOwn(LABELS, key)) return LABELS[key];
  return value.replace(/[_-]+/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()).replace(/\bVimax\b/g, 'ViMax');
}

export function localizeActivityText(value: string): string {
  if (Object.hasOwn(MESSAGES, value)) return MESSAGES[value];
  for (const [pattern, format] of MESSAGE_PATTERNS) {
    const match = value.match(pattern);
    if (match) return format(...match.slice(1));
  }
  // 未识别的动态内容和第三方错误保留原文，避免丢失诊断信息。
  return value;
}
